arb-dir: lib/l10n/arb
template-arb-file: app_es.arb
output-dir: lib/core/localization
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: untranslated.json
synthetic-package: false
