name: conecta_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  just_audio: ^0.9.38
  audio_service: ^0.18.12
  video_player: ^2.8.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  dio: ^5.5.0+1
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.2
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  timezone: ^0.9.3
  connectivity_plus: ^6.0.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
